FROM oven/bun:1.3.12

WORKDIR /app

# Instalar dependencias del sistema para Chrome
RUN apt-get update && apt-get install -y \
  libglib2.0-0 \
  libnss3 \
  libatk1.0-0 \
  libatk-bridge2.0-0 \
  libcups2 \
  libdrm2 \
  libxkbcommon0 \
  libxcomposite1 \
  libxdamage1 \
  libxfixes3 \
  libxrandr2 \
  libgbm1 \
  libasound2 \
  libpango-1.0-0 \
  libcairo2 \
  --no-install-recommends \
  && rm -rf /var/lib/apt/lists/*

COPY package.json bun.lockb ./
RUN bun install
RUN bunx puppeteer browsers install chrome@146.0.7680.31 --path ./puppeteer_data

COPY . .

CMD ["bun", "src/index.ts"]