import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideBar from "./sections/SideBar";
import Navbar from "./sections/Navbar";

const InterFont = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "BuildData",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${InterFont.variable}  h-full antialiased`}>
      <body className="min-h-screen flex flex-col">
        <Navbar />
        <main className="w-full grid grid-cols-10 grow">
          <SideBar />
          {children}
        </main>
      </body>
    </html>
  );
}
