import type { Obra, FileItem } from "@/types/projects";

export async function getObras(): Promise<Obra[]> {
  // TODO: Reemplazar con llamada real a la API
  // const res = await fetch(`${API_URL}/obras`);
  // return res.json();

  return [
    {
      id: "belgrano",
      name: "Edificio Belgrano",
      code: "OBR-2025-014",
      address: "Av. Belgrano 1842, CABA",
      type: "Edificio en altura",
      status: "en-curso",
      progress: 68,
      alerts: 2,
      pedidos: 7,
      team: ["JM", "CR", "PS", "LB", "MO"],
      lastActivity: "hace 12 min",
      lastActivityWho: "P. Salas reportó falla en grúa",
      starred: true,
      color: "#0F4395",
    },
    {
      id: "palermo",
      name: "Torre Palermo Norte",
      code: "OBR-2025-008",
      address: "Av. Santa Fe 4920, CABA",
      type: "Edificio en altura",
      status: "en-curso",
      progress: 42,
      alerts: 0,
      pedidos: 3,
      team: ["AG", "CR", "LB"],
      lastActivity: "hace 1 h",
      lastActivityWho: "C. Ríos subió 6 fotos",
      starred: true,
      color: "#0B3275",
    },
    {
      id: "villa-urquiza",
      name: "Casa Villa Urquiza",
      code: "OBR-2025-019",
      address: "Bauness 2104, CABA",
      type: "Vivienda unifamiliar",
      status: "planificacion",
      progress: 8,
      alerts: 1,
      pedidos: 2,
      team: ["JM", "AG"],
      lastActivity: "ayer 18:30",
      lastActivityWho: "A. Gómez cargó planos",
      starred: false,
      color: "#F59E0B",
    },
    {
      id: "oficinas-pilar",
      name: "Oficinas Pilar",
      code: "OBR-2024-031",
      address: "Ruta 8 km 49, Pilar",
      type: "Comercial / industrial",
      status: "en-curso",
      progress: 84,
      alerts: 0,
      pedidos: 1,
      team: ["JM", "MO", "LB", "PS", "CR", "AG"],
      lastActivity: "hoy 09:14",
      lastActivityWho: "L. Benítez aprobó pedido",
      starred: false,
      color: "#22C55E",
    },
    {
      id: "refaccion-recoleta",
      name: "Refacción Recoleta",
      code: "OBR-2024-022",
      address: "Junín 1410, CABA",
      type: "Refacción",
      status: "pausada",
      progress: 55,
      alerts: 3,
      pedidos: 0,
      team: ["MO", "PS"],
      lastActivity: "hace 5 días",
      lastActivityWho: "Obra en pausa por cliente",
      starred: false,
      color: "#94A3B8",
    },
    {
      id: "casa-tigre",
      name: "Casa de Fin de Semana · Tigre",
      code: "OBR-2024-007",
      address: "Canal San Fernando 280",
      type: "Vivienda unifamiliar",
      status: "finalizada",
      progress: 100,
      alerts: 0,
      pedidos: 0,
      team: ["JM", "AG", "CR"],
      lastActivity: "12 Mar 2025",
      lastActivityWho: "Entregada al cliente",
      starred: false,
      color: "#1A2238",
    },
  ];
}

export async function getFiles(): Promise<FileItem[]> {
  // TODO: Reemplazar con llamada real a la API
  return [
    { name: "Cronograma_Belgrano_v3.xlsx", kind: "xlsx", obra: "Edificio Belgrano", when: "hace 2 h", size: "1.2 MB" },
    { name: "Plano Sector C - planta 4.pdf", kind: "pdf", obra: "Edificio Belgrano", when: "ayer", size: "4.8 MB" },
    { name: "IMG_2034.jpg", kind: "img", obra: "Torre Palermo Norte", when: "hoy 10:15", size: "2.1 MB" },
    { name: "Pedido_PED-0142.pdf", kind: "pdf", obra: "Edificio Belgrano", when: "ayer 17:30", size: "180 KB" },
    { name: "Memoria descriptiva.docx", kind: "doc", obra: "Casa Villa Urquiza", when: "12 May", size: "420 KB" },
    { name: "Reporte_semanal_S20.pdf", kind: "pdf", obra: "Oficinas Pilar", when: "11 May", size: "900 KB" },
  ];
}
